[package]
name = "ycombinator-scraper-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html5ever = "0.26.0"
markup5ever = "0.11.0"
regex = "1.10.3"
serde = "1.0.197"
serde_json = "1.0.114"
soup = "0.5.1"
