name: Coverage

on: [pull_request, push]

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        options: --health-cmd="mongo --eval 'db.stats().ok'
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Install Chrome
        run: |
            chmod u+x ./scripts/install_chrome.sh
            ./scripts/install_chrome.sh
      - name: Create .env file
        run: echo "${{ secrets.TEST_VARIABLES }}" > .env
      - name: Generate code coverage
        run: cargo llvm-cov nextest --all-features --workspace --lcov --output-path lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Nneji123/workatastartup-scraper-rust
          files: lcov.info
          fail_ci_if_error: true
