name: Tests

on: [pull_request, push]

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable
      - name: Install Chrome
        run: chmod u+x ./scripts/install_chrome.sh && ./scripts/install_chrome.sh
      - name: Install dependencies
        run: cargo build
      - name: Run tests
        run: cargo test
